### ISSUE TITLE
Cross-client Authorization?

### ISSUE THREAD

**Issue by usmonster** [googleapis/google-auth-library-php#117]
Is (or will there be) support for cross-client auth, as described here:
https://developers.google.com/identity/protocols/CrossClientAuth#policy
?
Those docs aren't clear about how to do this outside of Android apps. Thanks!

**Comment by dwsupplee** [comment]
Hey there @usmonster,

I believe this should actually be supported through this library already:

```php
use Google\Auth\OAuth2;

$oauth = new OAuth2([
    'clientId' => $clientId,
    'clientSecret' => $clientSecret,
    'authorizationUri'   => $authUri,
    'tokenCredentialUri' => $tokenUri,
    'redirectUri'       => $redirectUri
]);

$oauth->setCode($authCode); // One time code received from the OAuth2 dialog
$token = $oauth->fetchAuthToken();
```

[Here's a stackoverflow post](https://stackoverflow.com/a/35209891) that may be helpful, as it is a provides at outline for how to achieve this with javascript instead of just Android.

I'm going to close this out for now, but if I've misunderstood your request or you have any more specific follow up questions feel free to re-open :).
