### ISSUE TITLE
Retrieve `expires_in` when new access token is fetched automatically from refresh token

### ISSUE THREAD

**Issue by djtarazona** [googleapis/google-auth-library-php#125]
The callback option #110 added is great, but it only provides the access token. But I'd also like to know when the access token is going to expire.  Why not pass the entire access token response to the callback?  I am updating my persistent store with the new access token, but need to know when it expires so that the refresh token (already stored) can be used if necessary.  And assuming an hour expiration isn't safe.

I suggest changing [AuthTokenMiddleware.php#L163](https://github.com/google/google-auth-library-php/blob/fe77e71bccf27ddf27141776913b98ad7279e03f/src/Middleware/AuthTokenMiddleware.php#L163) to:

``` php
call_user_func($this->tokenCallback, $this->getFullCacheKey(), $auth_tokens);
```

That way in the callback you can access `$auth_tokens['access_token']` and `$auth_tokens['expires_in']`.

If we need to make this change backwards compatible, we could always do this for now:

``` php
call_user_func($this->tokenCallback, $this->getFullCacheKey(), $auth_tokens['access_token'], $auth_tokens);
```

Please and thank you! :)

**Comment by vishwarajanand** [comment]
Sorry, it took so long for us to come back to it. The current code is [here](https://github.com/googleapis/google-auth-library-php/blob/90dc9c3ba6aa0a4d7c0c5bb4333504585c3cd82e/src/Middleware/ProxyAuthTokenMiddleware.php#L127).

Currently, we are not heavily using this codepath. And making this change, seems to be bringing more issues, such as duplicate params to the `tokenCallback`, etc. I think we better drop this since its already covered by https://github.com/googleapis/google-auth-library-php/pull/479
