### ISSUE TITLE
Creating client with credentials from secrets manager

### ISSUE THREAD

**Issue by ejohn20** [googleapis/google-auth-library-php#187]
Question: right now, the credentials are read from the file system by default. We have a requirement that does not allow us to store private keys at rest on disk. We have a secrets management solution in place that will allow us to pass the JSON directly to the Google Client. What is the best way to do this? Is there an overload similar to this somewhere that we can call to configure non-file system based API keys?

```
$client = new Google_Client;
$client->useCredentials($json);
....
```

**Comment by lenardpalko** [comment]
It would be also easier for Kuberentes deployments to pass the credentials to the containers.

From what I see currently the contents of the JSON file from disk are loaded into config as an array and there is no possibility to load credentials other than file.
How about having the possibility to store credential JSON directly in env variable instead of file ? 

Thanks

**Comment by lenardpalko** [comment]
Actually just noticed that at least for LoggingClient you can do something like : new LoggingClient(['keyFile' => <decoded_json_file>]);
Not sure if this is possible with other clients also.
