### ISSUE TITLE
Missing throwing Google_Service_Exception from OAuth2::fetchAuthToken

### ISSUE THREAD

**Issue by podolinek** [googleapis/google-auth-library-php#317]
Hi,

I changed google password and my authorized app stop working without handled error at place I expected (token refresh). Finally I found reason. At beginning of processing my request I have `$this->googleClient->refreshToken($this->googleClient->getRefreshToken())`.

`OAuth2.php::fetchAuthToken` - final method od this flow, returns string `{"error": "invalid_grant", "error_description": "Bad Request"}`.

I suppose correct should be throwing `Google_Service_Exception` with correct "400" code and message `{"error": "invalid_grant", "error_description": "Bad Request"}`.

It should be fixed by adding `\Google_Http_REST::decodeHttpResponse($response);` into `OAuth2.php::fetchAuthToken()`. But method `decodeHttpResponse` is in [api php client](https://github.com/googleapis/google-api-php-client). 

Ondrej

**Comment by bshaffer** [comment]
This library is completely separate from `google/apiclient`, so we do not want to add a call to `Google_Http_REST` because that class is not available to the stand-alone package.

I think this may be better handled in the `google/apiclient` package, to catch the exception and wrap it in `decodeHttpResponse`.

**Comment by bshaffer** [comment]
Closing because this is not something we plan to change. The proper approach is to catch auth errors separately.
