### ISSUE TITLE
Add compatibility with psr/cache 3.0

### ISSUE THREAD

**Issue by akalongman** [googleapis/google-auth-library-php#342]
I am not able to install this package, because this requires a downgrading of my `psr/cache` from 3.0 to 1.0

**Comment by bshaffer** [comment]
This update will require a BC-break, so we should target it for v2.0 (see #322)

@akalongman What are you using `google/auth` for? As a stand-alone library, or as part of another library?

**Comment by bshaffer** [comment]
After looking into this, compatibility with `psr/cache:3.0` will be difficult because it requires incompatibility with `psr/cache:1.0`. This means we'd essentially have to require PHP 8.0 to support it.

Another option would be to have two of every `psr/cache`-implementing classes. I am not a huge fan of this approach, but I don't see another way.

**Comment by akalongman** [comment]
@bshaffer I use this package with google apiclient.

**Comment by bshaffer** [comment]
@akalongman we've added support for `psr/cache:2.0` in #344. As long as the library you're using also allows `2.0` then this will work without an issue once we tag our next release.

**Comment by bshaffer** [comment]
fixed in #154
