### ISSUE TITLE
Cannot use ServiceAccountJwtAccessCredentials (no audience set) 

### ISSUE THREAD

**Issue by saranshdhingra** [googleapis/google-auth-library-php#400]
The issue has been migrated from [google-cloud-php#1130](https://github.com/googleapis/google-cloud-php/issues/1130)

```php
use Google\Auth\Credentials\ServiceAccountJwtAccessCredentials;
use Google\Cloud\PubSub\PubSubClient;

$cred = new ServiceAccountJwtAccessCredentials('/path/to/service-account.json');
$pubsub = new PubSubClient([
    'credentialsFetcher' => $cred,
    'projectId' => 'my-project-id'
]);
$topic = $pubsub->topic('my-topic');
var_dump($topic->exists());
```

throws:

```
Fatal error: Uncaught Google\Cloud\Core\Exception\ServiceException: {
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}
```

The audience is never being set on the credentials so it never loads an access token to use for authentication (and does this silently). The java library, for example, will throw and exception if there's no audience set.

**Comment by bshaffer** [comment]
The way these credentials were implemented, for better or for worse, was to pass the audience in at runtime to the credentials (e.g. when `updateMetadata` is called) rather than when `fetchAuthToken` is called. This is how all the language auth libraries were originally written, and I believe they still all function this way. 

The second part of this is what to do when the audience is empty. In most cases, the libraries return empty credentials. That's what this library has chosen to do. If other libraries decided to throw an exception, that's a separate design choice, but it's a matter of implementation. 

Adding an exception now would be a breaking change. Also, I'm not sure it'd be desirable even if it wasn't. So I'm closing this as Working As Designed.
