### ISSUE TITLE
openssl_verify() error on OIDC authentication

### ISSUE THREAD

**Issue by wkopala** [googleapis/google-auth-library-php#457]
I'm trying to authenticate a Cloud Scheduler job in PHP Laravel with this basic code:
    	$token = request()->bearerToken();

        if(!$token) {
            throw new Exception('Missing Auth header');
        }
        
        $auth = new AccessToken();
		$auth->verify($token, [
                'audience' => $audienceUrl,
                'throwException' => true,
            ]);
When I try to run the job, I keep getting this vague error:
openssl_verify(): Supplied key param cannot be coerced into a public key

Commenting out the auth code, the job runs just fine. Not sure what I'm doing wrong?

**Comment by TheFetchZen** [comment]
We are also experiencing a similar issue

```
ErrorException: openssl_verify(): supplied key param cannot be coerced into a public key in /var/www/html/vendor/firebase/php-jwt/src/JWT.php:301 
It seems that the Google/Auth library might be causing the issue.
```

See the below stacktrace
```#1 /var/www/html/vendor/firebase/php-jwt/src/JWT.php(301): openssl_verify('JSUzI...', '\xAF2\xEF\xB0\xF6[\xE1\xBD\xE3\xCE\xA5\f\xC0\xE8\x05...', '-----BEGIN RSA ...', 'SHA256') #2 /var/www/html/vendor/firebase/php-jwt/src/JWT.php(144): Firebase\JWT\JWT::verify('JSUzI...', '\xAF2\xEF\xB0\xF6[\xE1\xBD\xE3\xCE\xA5\f\xC0\xE8\x05...', '-----BEGIN RSA ...', 'RS256') #3 [internal function]: Firebase\JWT\JWT::decode('eyJhbGciOiJSUzI...', Array) #4 /var/www/html/vendor/google/auth/src/AccessToken.php(474): call_user_func_array(Array, Array) #5 /var/www/html/vendor/google/auth/src/AccessToken.php(249): Google\Auth\AccessToken->callJwtStatic('decode', Array)```

**Comment by krzyc** [comment]
Same problem here - switching to PKCS#8 resolves issue.
It is related to using obsolete version of OpenSSL (1.1.1).
But problem lies in phpseclib3 compatibility update (https://github.com/googleapis/google-auth-library-php/pull/425)
phpseclib2 used PKCS#8 by default, so upgrading to 1.26 and phpseclib3 can be breaking change.
Because it is **undocumented** and **inconsistent** change (1.25 used PKCS#8, 1.26 uses PKCS#1 when used with with phpseclib3 or PKCS#8 when used with phpseclib2) I treat it is as a bug which can be fixed by PR #466.
Affected versions are 1.26 to current (1.28) and in my opinion should be fixed ASAP.
If it is intended change it should be consistent and described in changelog.

**Comment by bshaffer** [comment]
@krzyc thank you for looking into this. It seems like you're right that #466 is a better solution, as it will revert the mistake made in #425 

I've merged the fix. Thanks for investigating and identifying the issue!

**Comment by bshaffer** [comment]
Fixed in https://github.com/googleapis/google-auth-library-php/releases/tag/v1.29.1
